---
title: "My cool project"
author: "Jacquie Tran"
date: "18 August 2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

Let's take a look at some data using the **{palmerpenguins}** R package by [Allison Horst](https://github.com/allisonhorst/palmerpenguins). First, load up the package itself.

```{r load_package}

# Install the {palmerpenguins} package if you need to:
# install.packages("palmerpenguins")

library(palmerpenguins)

```

Now check the first few rows of the penguins data set that is included in the **{palmerpenguins}** package.

```{r check_penguins_data}

head(penguins)

```

Finish with a plot of penguin body mass by species!

```{r plot_penguins_data}

# Install the {ggplot2} package if you need to:
# install.packages("ggplot2)

# Load ggplot2 for plotting
library(ggplot2)

# Make a plot using the penguins data
p <- ggplot(
  data = penguins,
  aes(x = body_mass_g, y = species, colour = species))
p <- p + geom_boxplot(width = 0.5, size = 1)
p <- p + geom_jitter(height = 0.2, alpha = 0.5, size = 3)

# Display the plot
p

```

